defmodule Desktop.WxStub do
  @moduledoc false

  # Generates src/desktop_wx.erl before any compiler runs.
  # - MIX_TARGET host (or unset) + wx.hrl resolvable by erlc → include_lib + ?wx macros
  # - android / ios / wx.hrl missing / wx.hrl not resolvable → header-free integer fallbacks

  @constant_names ~w(
    ID_ANY ID_EXIT DEFAULT_FRAME_STYLE NO_BORDER EXPAND HORIZONTAL VERTICAL
    ITEM_SEPARATOR ITEM_NORMAL ITEM_CHECK ITEM_RADIO
    ICON_WARNING ICON_ERROR ICON_QUESTION ICON_INFORMATION
    MAJOR_VERSION MINOR_VERSION RELEASE_NUMBER IMAGE_QUALITY_HIGH
  )

  @fallback %{
    wxID_ANY: -1,
    wxID_EXIT: 5006,
    wxDEFAULT_FRAME_STYLE: 541_072_960,
    wxNO_BORDER: 2_097_152,
    wxEXPAND: 8192,
    wxHORIZONTAL: 4,
    wxVERTICAL: 8,
    wxITEM_SEPARATOR: -1,
    wxITEM_NORMAL: 0,
    wxITEM_CHECK: 1,
    wxITEM_RADIO: 2,
    wxICON_WARNING: 256,
    wxICON_ERROR: 512,
    wxICON_QUESTION: 1024,
    wxICON_INFORMATION: 2048,
    wxMAJOR_VERSION: 0,
    wxMINOR_VERSION: 0,
    wxRELEASE_NUMBER: 0,
    wxIMAGE_QUALITY_HIGH: 192
  }

  @spec write!(Path.t()) :: :ok
  def write!(root \\ Path.expand("../../..", __DIR__)) do
    target = System.get_env("MIX_TARGET", "host")
    path = Path.join([root, "src", "desktop_wx.erl"])
    File.mkdir_p!(Path.dirname(path))

    body =
      if host_target?() and wx_headers_resolvable?() do
        hrl_body(target)
      else
        stub_body(target)
      end

    File.write!(path, body)
    :ok
  end

  defp host_target? do
    System.get_env("MIX_TARGET") in [nil, "host"]
  end

  # True only when both `wx.hrl` exists on disk AND the host's `erlc` can
  # resolve it through the OTP include path. Some hosts (e.g. the
  # `erlef/setup-beam` GHA Linux CI used by `diode-drive`) report a path
  # via `:code.lib_dir(:wx)` and have `wx.hrl` on disk, but the `erlc`
  # that `mix` invokes fails with `can't find include lib "wx/include/wx.hrl"`.
  # Probing with a throwaway include is the only reliable way to tell.
  def wx_headers_resolvable? do
    with lib when is_list(lib) <- :code.lib_dir(:wx),
         true <- File.exists?(Path.join([List.to_string(lib), "include", "wx.hrl"])),
         {:ok, _} <- probe_include_lib() do
      true
    else
      _ -> false
    end
  end

  defp probe_include_lib do
    src = Path.join(System.tmp_dir!(), "desktop_wx_probe.erl")
    out = Path.join(System.tmp_dir!(), "desktop_wx_probe.beam")

    try do
      File.write!(
        src,
        "-module(desktop_wx_probe).\n-include_lib(\"wx/include/wx.hrl\").\n-export([ok/0]).\nok() -> 1.\n"
      )

      case System.cmd("erlc", ["-o", System.tmp_dir!(), src], stderr_to_stdout: true) do
        {_out, 0} -> {:ok, :ok}
        other -> other
      end
    after
      File.rm(src)
      File.rm(out)
    end
  end

  defp hrl_body(target) do
    gets =
      @constant_names
      |> Enum.sort()
      |> Enum.map(fn name -> "get(wx#{name}) -> ?wx#{name}" end)
      |> Enum.join(";\n  ")

    """
    -module(desktop_wx).
    -include_lib("wx/include/wx.hrl").
    -export([get/1]).

    %% Generated by desktop_wx_stub.exs — do not edit.
    %% MIX_TARGET=#{target} — values from wx/include/wx.hrl

    #{gets}.
    """
  end

  defp stub_body(target) do
    gets = for {name, value} <- @fallback, do: "get(#{name}) -> #{value}"

    """
    -module(desktop_wx).
    -export([get/1]).

    %% Generated by desktop_wx_stub.exs — do not edit.
    %% MIX_TARGET=#{target} — header-free fallbacks (no wx.hrl / :wx)

    #{Enum.join(gets, ";\n  ")}.
    """
  end
end
