defmodule Desktop.WxStub do
  @moduledoc false

  # Generates src/desktop_wx.erl before any compiler runs.
  # - MIX_TARGET host (or unset) + wx.hrl present → include_lib + ?wx macros
  # - android / ios / no wx headers → header-free integer fallbacks

  @constant_names ~w(
    ID_ANY ID_EXIT DEFAULT_FRAME_STYLE NO_BORDER EXPAND HORIZONTAL VERTICAL
    ITEM_SEPARATOR ITEM_NORMAL ITEM_CHECK ITEM_RADIO
    ICON_WARNING ICON_ERROR ICON_QUESTION ICON_INFORMATION
    MAJOR_VERSION MINOR_VERSION RELEASE_NUMBER IMAGE_QUALITY_HIGH
  )

  @fallback %{
    wxID_ANY: -1,
    wxID_EXIT: 5006,
    wxDEFAULT_FRAME_STYLE: 541_072_960,
    wxNO_BORDER: 2_097_152,
    wxEXPAND: 8192,
    wxHORIZONTAL: 4,
    wxVERTICAL: 8,
    wxITEM_SEPARATOR: -1,
    wxITEM_NORMAL: 0,
    wxITEM_CHECK: 1,
    wxITEM_RADIO: 2,
    wxICON_WARNING: 256,
    wxICON_ERROR: 512,
    wxICON_QUESTION: 1024,
    wxICON_INFORMATION: 2048,
    wxMAJOR_VERSION: 0,
    wxMINOR_VERSION: 0,
    wxRELEASE_NUMBER: 0,
    wxIMAGE_QUALITY_HIGH: 192
  }

  @spec write!(Path.t()) :: :ok
  def write!(root \\ Path.expand("../../..", __DIR__)) do
    target = System.get_env("MIX_TARGET", "host")
    path = Path.join([root, "src", "desktop_wx.erl"])
    File.mkdir_p!(Path.dirname(path))

    body =
      if host_target?() and wx_headers_exist?() do
        hrl_body(target)
      else
        stub_body(target)
      end

    File.write!(path, body)
    :ok
  end

  defp host_target? do
    System.get_env("MIX_TARGET") in [nil, "host"]
  end

  defp wx_headers_exist? do
    case :code.lib_dir(:wx) do
      path when is_list(path) ->
        File.exists?(Path.join([List.to_string(path), "include", "wx.hrl"]))

      _ ->
        false
    end
  end

  defp hrl_body(target) do
    gets =
      @constant_names
      |> Enum.sort()
      |> Enum.map(fn name -> "get(wx#{name}) -> ?wx#{name}" end)
      |> Enum.join(";\n  ")

    """
    -module(desktop_wx).
    -include_lib("wx/include/wx.hrl").
    -export([get/1]).

    %% Generated by desktop_wx_stub.exs — do not edit.
    %% MIX_TARGET=#{target} — values from wx/include/wx.hrl

    #{gets}.
    """
  end

  defp stub_body(target) do
    gets = for {name, value} <- @fallback, do: "get(#{name}) -> #{value}"

    """
    -module(desktop_wx).
    -export([get/1]).

    %% Generated by desktop_wx_stub.exs — do not edit.
    %% MIX_TARGET=#{target} — header-free fallbacks (no wx.hrl / :wx)

    #{Enum.join(gets, ";\n  ")}.
    """
  end
end
